######################################################################
#
# File name : MM_Ultra_tb_compile.do
# Created on: Sun Sep 08 21:57:52 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  "+incdir+../src" \
"../src/AdderS.v" \
"../src/MM.v" \
"../src/MM_buffer.v" \
"../src/MM_in_buffer.v" \
"../src/MM_out_buffer.v" \
"../src/MM_ultra.v" \
"../src/PE.v" \
"../src/PE_array.v" \
"../src/PE_line.v" \
"../src/right_shifter.v" \

vlog  -incr -mfcu -sv -work xil_defaultlib "+incdir+../src" "+incdir+../sim" \
"../sim/MM_Ultra_tb.sv" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

# quit -force

