######################################################################
#
# File name : MM_Ultra_tb_simulate.do
# Created on: Sun Sep 08 21:57:54 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
# vsim -voptargs="+acc" -lib xil_defaultlib xil_defaultlib.MM_Ultra_tb xil_defaultlib.glbl
vsim -c -debugDB -voptargs=+acc -lib xil_defaultlib xil_defaultlib.MM_Ultra_tb xil_defaultlib.glbl

radix hex
radix unsigned

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {MM_Ultra_tb_wave.do}

view wave
view structure
view signals

do {MM_Ultra_tb.udo}

run 1000ns

run -all
