######################################################################
#
# File name : MM_Ultra_tb_wave.do
# Created on: Sun Sep 08 21:57:54 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
