######################################################################
#
# File name : MM_Ultra_tb_wave.do
# Created on: Sun Sep 08 21:57:54 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /MM_Ultra_tb/u_MM_ultra/*
# add wave -r -radix hex /MM_Ultra_tb/u_MM_ultra/*
add wave /MM_Ultra_tb/u_MM_ultra/u_MM_buffer/*
add wave /glbl/GSR


